---
title: ""
output: html_notebook
---

## These are the maps of conservation of African

load the libraries

```{r}
library(tidyverse)
library(sf)
library(terra)
library(grid)
```

load the data

```{r}
afriSHP <- read_sf()

print(afriSHP)
```

```{r}
biodivRAST <- rast()
print(biodivRAST)
```

extract the biodiversity dat

```{r}
biodivRAST <- extract(afriSHP, biodivRAST)
print(biodivRAST)

```

join this data back to the shapefile dataset

```{r}
afriSHP$biodiv <- biodivRAST$biodivRast

print(afriSHP)


```

join the Intactness Index, country and funding to the shapefile

```{r}

```

# creating map of Funding

```{r}
funding = ggplot()+geom_sf(afriSHP, aes(Funding))
```

# creating map of biodiversity

```{r}
biodiv = ggplot()+geom_sf(afriSHP, aes(biodiv))

```

# creating map of intactness index

```{r}
I.index = ggplot()+geom_sf(afriSHP, aes(biodiv))

```

# plot all 3 maps ata high resolution 

```{r}
Maps <- ggrid(funding,
              biodiv, 
              I.index, )
```
